# Generated by Django 5.2.7 on 2025-10-28 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_categories', to='stock.category'),
        ),
        migrations.AlterField(
            model_name='purchaseitems',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchased_products', to='stock.products'),
        ),
        migrations.AlterField(
            model_name='purchaseitems',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items_from_suppliers', to='stock.suppliers'),
        ),
    ]
