# Generated by Django 5.2.7 on 2025-10-22 15:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stock', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('Mpesa', 'mpesa'), ('Cash', 'cash'), ('Credit', 'credit')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('mpesa_code', models.CharField(blank=True, max_length=50, null=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SalesClerk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateTimeField(auto_now_add=True)),
                ('check_out', models.DateTimeField(auto_now_add=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clerk_details', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SaleItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_created=True)),
                ('cust_name', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity', models.PositiveIntegerField()),
                ('selling_price', models.DecimalField(decimal_places=2, editable=False, max_digits=8)),
                ('buying_price', models.DecimalField(decimal_places=2, editable=False, max_digits=8)),
                ('profit', models.DecimalField(decimal_places=2, editable=False, max_digits=8)),
                ('total', models.DecimalField(decimal_places=2, editable=False, max_digits=8)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_profit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sales_payment_type', to='sales.paymentmethod')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sold_items', to='stock.products')),
                ('sales_clerk', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sales_by', to='sales.salesclerk')),
            ],
        ),
    ]
