# Generated by Django 5.2.7 on 2025-10-28 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
        ('stock', '0002_alter_products_category_alter_purchaseitems_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleitems',
            name='payment_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_payment_type', to='sales.paymentmethod'),
        ),
        migrations.AlterField(
            model_name='saleitems',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sold_items', to='stock.products'),
        ),
        migrations.AlterField(
            model_name='saleitems',
            name='sales_clerk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_by', to='sales.salesclerk'),
        ),
    ]
